/*
 * Copyright 2021 dev.id
 */
package es.littledavity.database

internal object Constants {

    const val DATABASE_NAME = "chorboagenda-db"
    const val VERSION = 1
    const val ENTITIY_AUTOGENERATED_ID_INDICATOR = 0
    const val CHORBOAGENDA_DATABASE_EXPORT_SCHEMA = false
}
