package es.littledavity.database.chorbo.datastores

import com.paulrybitskyi.hiltbinder.BindType
import es.littledavity.core.providers.TimestampProvider
import es.littledavity.data.contacts.DataContact
import es.littledavity.database.Constants
import es.littledavity.database.chorbo.entities.Contact
import javax.inject.Inject

internal interface SaveContactFactory {
    fun createContact(contact: DataContact): Contact
}

@BindType
internal class SaveContactFactoryImpl @Inject constructor(
    private val timestampProvider: TimestampProvider
) : SaveContactFactory {

    override fun createContact(contact: DataContact) = Contact(
        id = Constants.ENTITIY_AUTOGENERATED_ID_INDICATOR,
        name = contact.name,
        image =  contact.image,
        phone = contact.phone,
        timestampProvider.getUnixTimestamp()
    )
}